import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import useRedirect from "@/custom-hooks/use-redirect";
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { redirectTo } = useRedirect();
  useEffect(() => {
    redirectTo("/auth/login");
  }, []);

  return (
    <>
      {/* <Head>
      
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>hello</h1>
      </main> */}
    </>
  );
}
